[database]
    name     = "vulcanize_public"
    hostname = "localhost"
    port     = 5432
    password = "password"
    user     = "vdbm"

[validate]
    block-height = 1
    trail        = 10

[chain]
    set = true
    chainid = 4
    homestead-block = 1
    fork-block  = 0
    fork-support = true
    eip150-block = 2
    eip150-hash = "0x9b095b36c15eaf13044373aef8ee0bd3a382a5abb92e402afa44b8249c3a90e9"
    eip155-block = 3
    eip158-block = 3
    byzantium-block = 1035301
    constantinople-block = 3660663
    petersburg-block = 4321234
    istanbul-block = 5435345
    muirGlacier-block = 0
    berlin-block = 8_290_928
    london-block = 987988
    arrowGlacier-block = 0
    mergeFork-block = 0
    ethash = false
    clique-period = 15
    clique-epoch = 30000